### ISSUE TITLE
Operaciones Básicas de Sistemas Numéricos

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Eddi3mendoz#1]
[Practica individual Operaciones basicas de sistemas numericos.pdf](https://github.com/user-attachments/files/16861281/Practica.individual.Operaciones.basicas.de.sistemas.numericos.pdf)

**Comment by ANGELGARCIASANTIAGO** [comment]
Portada:25/25
Procedimiento:25/25
Figuras ilustraciones y fotografías :25/25
Resultados y conclusiones:25/25
Calificación final:20

**Comment by mae18-25** [comment]
> Portada:25/25 Procedimiento:25/25 Figuras ilustraciones y fotografías :25/25 Resultados y conclusiones:25/25 Calificacion final:20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
